server:
  port: 8087
spring:
  application:
    name: app-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8100/eureka,http://admin:123456@127.0.0.1:9100/eureka
    # 因为该应用为服务提供者，是eureka的一个客户端，因此需要注册到注册中心
    register-with-eureka: true
    # 是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    #将自己IP地址注册到eureka服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}##${server.port}
zuul:
  #定义服务转发规则
  routes:
    shop-item-service: #名字随意取，但是尽量和业务名称相关
      #配置请求URL的请求规则
      path: /shop-item-service/**
      #实际微服务地址，path匹配的请求都转发到这里
      #url: http://127.0.0.1:8081
      serviceid: shop-item #改成从eureka中获取，以下一样
    shop-order-service:
      path:/shop-order-service/**
      serviceid: shop-order


