server:
  port: 8082

spring:
  application:
    name: shop-order



#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
    #因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    fetch-registry: true
