server:
  port: 8082

spring:
  application:
    name: shop-order



#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      #defaultZone: http://127.0.0.1:8100/eureka
      # 单例 eureka server模式
      #defaultZone: http://admin:123456@127.0.0.1:8100/eureka
      # 集群模式
      defaultZone: http://admin:123456@127.0.0.1:8100/eureka,http://admin:123456@127.0.0.1:9100/eureka
    #因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    fetch-registry: true
  instance:
    # 指定IP，将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # 通过instance-id 参数指定服务注册到Eureka中的服务实例id
    instance-id: ${spring.application.name}##${server.port}


#设定负载均衡策略，其中，shop-item 为要访问的应用ID
#PredicateBasedRule 默认策略，综合判断Server所在区的性能和server的可用性
#RoundRobinRule 线性轮询
#RandomRule 随机
#RetryRule 重试机制，默认使用RoundRobinRule策略
shop-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#开启Hystrix断路器
feign:
  hystrix:
    enabled: true
