server:
  port: 8100

#server name
spring:
  application:
    name: app-eureka-sn
  security:
#    basic:
#      #开启基于HTTP basic的认证
#      enable: true
    user:
      # config user account
      name: admin
      password: 123456

eureka:
  instance:
    #regist center address
    hostname: 127.0.0.1
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:8100/eureka
      # 添加security后，上述地址就调整为以下样式
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka
    #是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
    register-with-eureka: false
    #是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息
    fetch-registry: false

  # 禁用自我保护（开发环境一般建议禁用自我保护）
  server:
    enable-self-preservation: false